force-app/main/default/objects/SCVSimulator_Conversation__c/SCVSimulator_Conversation__c.object-meta.xml
<CustomObject>
    <label>SCV Simulator Conversation</label>
    <nameField>
        <label>SCV Simulator Conversation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SCV Simulator Conversations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SCVSimulator_Conversation_Message__c/SCVSimulator_Conversation_Message__c.object-meta.xml
<CustomObject>
    <label>SCV Simulator Conversation Message</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>SCV Simulator Conversation Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCV Simulator Conversation Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SCVSimulator_Conversation_Message__c/fields/Conversation_Order__c.field-meta.xml
<CustomField>
    <fullName>Conversation_Order__c</fullName>
    <label>Conversation Order</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SCVSimulator_Conversation_Message__c/fields/Message_Type__c.field-meta.xml
<CustomField>
    <fullName>Message_Type__c</fullName>
    <label>Message Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SCVSimulator_Conversation_Message__c/fields/SCVSimulator_Conversation__c.field-meta.xml
<CustomField>
    <fullName>SCVSimulator_Conversation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SCV Simulator Conversation</label>
    <referenceTo>SCVSimulator_Conversation__c</referenceTo>
    <relationshipLabel>SCV Simulator Conversation Messages</relationshipLabel>
    <relationshipName>SCVSimulator_Conversation_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SCVSimulator_ConversationChange__e/SCVSimulator_ConversationChange__e.object-meta.xml
<CustomObject>
    <label>SCVSimulator Conversation Change</label>
    <pluralLabel>SCVSimulator Conversation Changes</pluralLabel>
</CustomObject>

force-app/main/default/objects/SCVSimulator_ConversationChange__e/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SCVSimulator_CT.cls
public class SCVSimulator_CT {
    
    @AuraEnabled
    public static void publishPlatformEvent(Decimal newStage) {
        SCVSimulator_ConversationChange__e  conversationPlatformEvt = new SCVSimulator_ConversationChange__e();
        conversationPlatformEvt.Stage__c = newStage;
        EventBus.publish(conversationPlatformEvt);
    }
	
    @AuraEnabled
    public static SCVSimulator_ConversationWrapper fetchConversation(String conversationId, String voiceCallRecordId){
        return new SCVSimulator_ConversationWrapper(conversationId, voiceCallRecordId);
    }
    
    public class SCVSimulator_ConversationWrapper {
        @AuraEnabled public SCVSimulator_Conversation__c conversation {get; set;}
        @AuraEnabled public List<SCVSimulator_Conversation_Message__c> messages {get; set;}
        
        public SCVSimulator_ConversationWrapper(String conversationId, String voiceCallRecordId) {
            
            this.conversation = [SELECT Id FROM SCVSimulator_Conversation__c WHERE Id = :conversationId LIMIT 1];
            
            this.messages = [SELECT Id, SCVSimulator_Conversation__c, Message__c, Conversation_Order__c, Message_Type__c
                             FROM SCVSimulator_Conversation_Message__c 
                             WHERE SCVSimulator_Conversation__c =:conversationId 
                             ORDER BY Conversation_Order__c, LastModifiedDate ASC];
        }
    }
    
    @AuraEnabled
    public static void routeWork() {
        
        VoiceCall workItem = [SELECT Id FROM VoiceCall WHERE OwnerId =:UserInfo.getUserId() ORDER BY CallStartDateTime desc LIMIT 1];
        ServiceChannel channel = [SELECT Id FROM ServiceChannel WHERE MasterLabel ='Phone'];
        
        AgentWork work = new AgentWork();
        work.WorkItemId = workItem.Id;
        work.ServiceChannelId = channel.Id;    
        work.UserId = UserInfo.getUserId();
        
        insert work;
   
    }

}