force-app/main/default/objects/Individual_Email_Results__c/Individual_Email_Results__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Individual Email Results</label>
</CustomObject>

force-app/main/default/objects/Individual_Email_Results__c/fields/Bounced__c.field-meta.xml
<CustomField>
    <fullName>Bounced__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bounced</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Individual_Email_Results__c/fields/Clicked__c.field-meta.xml
<CustomField>
    <fullName>Clicked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Clicked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Individual_Email_Results__c/fields/Email_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_Name__c</fullName>
    <label>Email Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Journeys__c/Journeys__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Journeys</label>
</CustomObject>

force-app/main/default/objects/Journeys__c/fields/Name_of_Communication__c.field-meta.xml
<CustomField>
    <fullName>Name_of_Communication__c</fullName>
    <label>Name of Communication</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MarketingCloudEngagementHistoryCtrl.cls
public class MarketingCloudEngagementHistoryCtrl  {
    
    @AuraEnabled
    public static customSettingDetails getCustomSettingsData(String customSettingName){
       
        CustomSettingDetails csd = new CustomSettingDetails();
        String soql='';
        if(customSettingName == 'Journeys'){
            soql = 'select Channel__c, Date_Sent__c , Name_of_Communication__c from Journeys__c';
            csd.colHeaders = new List<string>{'Name of Communication', 'Channel', 'Date Sent'};
            csd.records.addAll(Database.query(soql));
        }else if (customSettingName == 'Individual Email Results'){
            soql= 'select Bounced__c, Email_Name__c, Date_Sent__c, Opened__c, Clicked__c from Individual_Email_Results__c ';
            csd.colHeaders = new List<string>{'Email Name', 'Date Sent', 'Opened', 'Clicked', 'Bounced'};
            csd.records.addAll(Database.query(soql)); 
        }
        system.debug('csd$$$$$' + csd);
       return csd;
    }
    
    public class CustomSettingDetails{
        @AuraEnabled
        public List<String> colHeaders{get;set;}
        @AuraEnabled
        public List<Sobject> records{get;set;}
        public customSettingDetails(){
            records = new List<Sobject>();
        }
    }
}