force-app/main/default/objects/FINS_Distributed_Marketing_Content__c/FINS_Distributed_Marketing_Content__c.object-meta.xml
<CustomObject>
    <description>Used by the Mock Distributed Marketing Component to simulate distributed marketing data.</description>
    <label>Distributed Marketing Content</label>
    <nameField>
        <label>Distributed Marketing Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distributed Marketing Content</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FINS_Distributed_Marketing_Content__c/fields/Distributed_Marketing_Template__c.field-meta.xml
<CustomField>
    <fullName>Distributed_Marketing_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributed Marketing Template</label>
    <referenceTo>FINS_Distributed_Marketing_Template__c</referenceTo>
    <relationshipLabel>Distributed Marketing Content</relationshipLabel>
    <relationshipName>Distributed_Marketing_Content</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FINS_Distributed_Marketing_Content__c/fields/Layout__c.field-meta.xml
<CustomField>
    <fullName>Layout__c</fullName>
    <label>Layout</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Image Left</fullName>
            </value>
            <value>
                <fullName>Image Right</fullName>
            </value>
            <value>
                <fullName>Image Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FINS_Distributed_Marketing_Template__c/FINS_Distributed_Marketing_Template__c.object-meta.xml
<CustomObject>
    <label>Distributed Marketing Template</label>
    <nameField>
        <label>Distributed Marketing Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distributed Marketing Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FINS_Distributed_Marketing_Template__c/fields/Footer_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Footer_Image_URL__c</fullName>
    <label>Footer Image URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FINS_Distributed_Marketing_Template__c/fields/Header_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Header_Image_URL__c</fullName>
    <label>Header Image URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FINS_Distributed_Marketing_Template__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lending</fullName>
            </value>
            <value>
                <fullName>Retail Banking</fullName>
            </value>
            <value>
                <fullName>Wealth Management</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Commercial Banking</fullName>
            </value>
            <value>
                <fullName>Asset Management</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FINS_Distributed_Marketing_Template__c/fields/Logo_URL__c.field-meta.xml
<CustomField>
    <fullName>Logo_URL__c</fullName>
    <description>URL Path to Logo File</description>
    <label>Logo URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FINS_Distributed_Marketing_Template__c/fields/Primary_Description__c.field-meta.xml
<CustomField>
    <fullName>Primary_Description__c</fullName>
    <label>Primary Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/FINS_Distributed_Marketing_Template__c/fields/Primary_Header__c.field-meta.xml
<CustomField>
    <fullName>Primary_Header__c</fullName>
    <description>Heading text shown right below the Header Image</description>
    <label>Primary Header Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FINS_DistributedMarketingMock.cls
public class FINS_DistributedMarketingMock {
@AuraEnabled 
    public static List<FINS_Distributed_Marketing_Template__c > getTemplateContent() {
        List<FINS_Distributed_Marketing_Template__c > dmcontent = [Select Name,Footer_Image_URL__c,Id,Header_Image_URL__c ,Logo_URL__c ,Primary_Description__c ,Primary_Header__c,Industry__c From FINS_Distributed_Marketing_Template__c ORDER BY Name ASC]; 
        return dmcontent; 
    }
    @AuraEnabled 
    public static List<sObject> getRecordInfo(String recid) {
        Id rid = recId;
        Schema.SObjectType sobjectType = rid.getSObjectType();
        string type = String.valueOf(sobjectType);
        if(type == 'Account'){
            String checkType = [SELECT RecordType.Name FROM Account WHERE ID = :rid].RecordType.Name;
            if(checkType == 'Person Accounts' || (checkType == 'FSC Person Accounts' )){
                return [SELECT Name FROM Account WHERE ID = :rid];
            }
        }else if(type == 'Lead'){
            return [SELECT Name FROM Lead WHERE ID = :rid];
        }else if(type == 'Contact'){
            return [SELECT Name FROM Contact WHERE ID = :rid];
        }else{
            return null;
        }
        return null;
    }
    
    
	@AuraEnabled 
    public static List<FINS_Distributed_Marketing_Content__c > getContent(String template) {
        List<FINS_Distributed_Marketing_Content__c > dmcontent = [Select Name,Id, Layout__c  ,Distributed_Marketing_Template__r.Industry__c,Image_URL__c, Description__c, Distributed_Marketing_Template__c   From FINS_Distributed_Marketing_Content__c  WHERE Distributed_Marketing_Template__r.Name = :template ORDER BY Name ASC]; 
        return dmcontent; 
    } 
    
    @AuraEnabled 
    public static List < String > getselectOptions(sObject objObject, string fld) {
        List < String > allOpts = new list < String > ();
        // Get the object type of the SObject.
        Schema.sObjectType objType = objObject.getSObjectType();
        
        // Describe the SObject using its object type.
        Schema.DescribeSObjectResult objDescribe = objType.getDescribe();
        
        // Get a map of fields for the SObject
        map < String, Schema.SObjectField > fieldMap = objDescribe.fields.getMap();
        
        // Get the list of picklist values for this field.
        list < Schema.PicklistEntry > values =
            fieldMap.get(fld).getDescribe().getPickListValues();
        
        // Add these values to the selectoption list.
        for (Schema.PicklistEntry a: values) {
            allOpts.add(a.getValue());
        }
        allOpts.sort();
        return allOpts;
    }
}