force-app/main/default/objects/Hotspots__c/Hotspots__c.object-meta.xml
<CustomObject>
    <label>Hotspots</label>
    <nameField>
        <label>Hotspots Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotspots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotspots__c/fields/Prototype_Screen_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Prototype_Screen_Configuration__c</fullName>
    <label>Prototype Screen Configuration</label>
    <referenceTo>Prototype_Screen_Configuration__c</referenceTo>
    <relationshipLabel>Hotspots</relationshipLabel>
    <relationshipName>Hotspots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Hotspots__c/fields/Target_Screen__c.field-meta.xml
<CustomField>
    <fullName>Target_Screen__c</fullName>
    <label>Target Screen</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hotspots__c/fields/X_cordinate__c.field-meta.xml
<CustomField>
    <fullName>X_cordinate__c</fullName>
    <label>X-cordinate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Hotspots__c/fields/Y_cordinate__c.field-meta.xml
<CustomField>
    <fullName>Y_cordinate__c</fullName>
    <label>Y-cordinate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Prototype_Screen_Configuration__c/Prototype_Screen_Configuration__c.object-meta.xml
<CustomObject>
    <label>Prototype Screen Configuration</label>
    <nameField>
        <label>Prototype Screen Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prototype Screen Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Prototype_Screen_Configuration__c/fields/File_VersionId__c.field-meta.xml
<CustomField>
    <fullName>File_VersionId__c</fullName>
    <label>File VersionId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prototype_Screen_Configuration__c/fields/Prototype_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Prototype_Configuration__c</fullName>
    <label>Prototype Configuration</label>
    <referenceTo>PrototypeConfiguration__c</referenceTo>
    <relationshipLabel>Prototype Screen Configurations</relationshipLabel>
    <relationshipName>Prototype_Screen_Configurations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Prototype_Screen_Configuration__c/fields/sheight__c.field-meta.xml
<CustomField>
    <fullName>sheight__c</fullName>
    <label>Screen Height</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Prototype_Screen_Configuration__c/fields/startFlag__c.field-meta.xml
<CustomField>
    <fullName>startFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>startFlag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/HotspotViewerController.cls
public with sharing class HotspotViewerController {
    public HotspotViewerController() {

    }

    @AuraEnabled
public static List<FilesWrapper> getRelatedFiles(Id recordId){
    
    List<ContentDocument> cdList = new List<ContentDocument>();
    List<ContentDocumentLink> cdlList = [SELECT ContentDocumentId FROM ContentDocumentLink
                                         WHERE LinkedEntityId = :recordId];
    Set<Id> cdIds = new Set<Id>();
    List<FilesWrapper> lstFiles = new List<FilesWrapper>();
    for (ContentDocumentLink cdl : cdlList) {
        cdIds.add(cdl.ContentDocumentId); 
    }        
    cdList = [SELECT Id, Title, FileType, OwnerId, Owner.Name, CreatedDate,
              CreatedById, CreatedBy.Name, ContentSize
              FROM ContentDocument WHERE Id IN :cdIds];

    Map<Id,Prototype_Screen_Configuration__c> mapFildIdToPSC = new Map<Id,Prototype_Screen_Configuration__c>();
    List<Id> pscIds = new List<Id>();
    for( Prototype_Screen_Configuration__c psc : [SELECT Id,Name,startFlag__c,sheight__c, File_VersionId__c FROM Prototype_Screen_Configuration__c WHERE Prototype_Configuration__c =: recordId]) {
        mapFildIdToPSC.put( psc.File_VersionId__c, psc);
        pscIds.add(psc.Id);
    }
    Map<Id, List<Hotspots__c>>  mapPCSIdToHotspots = new Map<Id, List<Hotspots__c>>();
    for( Hotspots__c hsp : [SELECT Id, Height__c,Prototype_Screen_Configuration__c,Target_Screen__c,Target_URL__c,Width__c,X_cordinate__c,Y_cordinate__c FROM Hotspots__c WHERE Prototype_Screen_Configuration__c IN :pscIds]) {
        if( !mapPCSIdToHotspots.containsKey(hsp.Prototype_Screen_Configuration__c)) {
            mapPCSIdToHotspots.put(hsp.Prototype_Screen_Configuration__c, new List<Hotspots__c>());
        }
        mapPCSIdToHotspots.get( hsp.Prototype_Screen_Configuration__c).add(hsp);
    }

    for (ContentDocument cd : cdList) {
        ContentVersion cv = [SELECT Id FROM ContentVersion WHERE ContentDocumentId = :cd.Id AND IsLatest = true];
        String cvDownloadURL = URL.getSalesforceBaseUrl().toExternalForm() + '/sfc/servlet.shepherd/version/download/' + cv.Id;
        
            FilesWrapper fw = new FilesWrapper();
            fw.docId = cd.Id;
            fw.title = cd.Title;
            fw.fileType = cd.FileType;
            fw.contentVersionId = cv.Id;
            fw.docURL = cvDownloadURL;
            if( mapFildIdToPSC.containsKey(cv.Id) ) {
                fw.prototypeScreenConfig = mapFildIdToPSC.get(cv.Id);
                if( mapPCSIdToHotspots.containsKey(mapFildIdToPSC.get(cv.Id).Id) ) {
                    fw.hotspots = mapPCSIdToHotspots.get(mapFildIdToPSC.get(cv.Id).Id);
                }
            }
            
            
            lstFiles.add(fw);
        
        
    }

    return lstFiles;
}



public class FilesWrapper{

    @AuraEnabled
    public string docId { get; set;}

    @AuraEnabled
    public string title { get; set;}

    @AuraEnabled
    public string fileType { get; set;}

    @AuraEnabled
    public string contentVersionId { get; set;}
    
    @AuraEnabled
    public string docURL { get; set;}

    @AuraEnabled
    public Prototype_Screen_Configuration__c prototypeScreenConfig;
    
    @AuraEnabled
    public List<Hotspots__c> hotspots;


}

}